### ISSUE TITLE
Fatal error: Unable to find local grunt.

### ISSUE THREAD

**Issue by dmiric** [phase2/rig#71]
I'm trying to figure out how this whole rig setup works and I'm having trouble with using start.sh. Is there a guide somewhere how to setup a new project. I'm trying to figure things out from the documentation but its pretty hard to understand. 

Installation documentation is pretty clear but I find some missing links when I try to connect it all with rig.

``➜  rigtest bin/start.sh 
[INFO] Preparing site for environment 'local' using start.sh (v3.4.0)
[INFO] docker-compose -f docker-compose.yml up -d cache db
Starting rigtest_local_cache ... 
Starting rigtest_local_cache
Starting rigtest_local_db ... 
Starting rigtest_local_db ... done
[INFO] When grunt commands fail they suggest running with '--force'.
[INFO] This just suppresses errors and is unlikely to fix issues causing your build process to fail.
[INFO] docker-compose run --rm -e NPM_CONFIG_LOGLEVEL=error cli "npm install && grunt --timer --quiet "
grunt-cli: The grunt command line interface (v1.2.0)

Fatal error: Unable to find local grunt.

If you're seeing this message, grunt hasn't been installed locally to
your project. For more information about installing and configuring grunt,
please see the Getting Started guide:

http://gruntjs.com/getting-started
[ERROR] start.sh: Error: Line 13: eval
Stopping rigtest_local_db    ... done
Stopping rigtest_local_cache ... done
FAIL

start.sh: aborted (33)
 %                   ``

**Comment by grayside** [comment]
Hello @dmiric 

Thanks for filing your support/bug report and including useful background information.

Outrigger as a suite of tool, docker image, and documentation repos can be a confusing landscape to navigate to place an issue. The Rig CLI does not proscribe any particular details about the application and does not know about a start.sh.

### Triage

The `start.sh` script (which may have leaked into general documentation somewhere) is produced by the [Outrigger Drupal](https://github.com/phase2/generator-outrigger-drupal) generator project as part of it's default suite of scripts.

### Interpreting the Logs

If your project is properly set up from the generator, you will see the error message in the middle is referring to grunt. This is something that happens if you try to run `grunt` without a project gruntfile.js to facilitate the basic bootstrap.

### Troubleshooting

First, run `rig doctor` to confirm the overall heal of your Outrigger setup.

From here on, my troubleshooting directions assume the use of Outrigger Drupal to create the project you are working on.

From prior experience, this problem can often result from npm install silently failing (such as from VM disk capacity issues) or from file sharing between the host machine and the Docker container.

Without knowing what your alias `rigtest` does it is hard to say, but bin/start.sh should be run from your local host. If the project is using unison file syncing (instead of the previously preferred NFS file mount) you will need to have previously run `rig project sync` to start that up.

Note that projects generated with a version of Outrigger Drupal since June should use `rig project setup` for first-time setup.

If Unison is not part of your project setup, then we should confirm that the necessary prerequisites for Grunt make it into your container. You can test that with:

```
docker-compose up -d
docker-compose -f build.yml run --rm cli
ls -l Grunfile.js
ls -l node_modules/grunt
```

**Comment by dmiric** [comment]
Hello,

Thank you for the reply. 

Yes I generated the project with Outrigger Drupal generator.

When I use rig doctor i get the following output:

```
[INFO] Docker is installed.
[INFO] Docker Compose is installed.
[ERROR] No machine named 'dev' exists. Did you run 'rig start --name="dev"'?
```

Since I have posted 2 different support tickets maybe we could just continue here:
https://github.com/phase2/outrigger-dashboard/issues/6#issuecomment-331944609

**Comment by febbraro** [comment]
I think the main issue here is by default outrigger attempts to use unison volumes, but it doesn't need to when it is on linux.  If you look at the build.yml file you will likely see under `volumes` something like `project-sync:/var/www` If you see that, replace `project-sync` with `.` and when you run again things should get further along.

**Comment by dmiric** [comment]
Hello @febbraro

Sorry to say but that did not help.

Should rig start be doing the same as bin/start.sh ?

I also tried rig project setup I get following:

```
Welcome to the Project!
Please review the README.md, CONTRIBUTING.md, TODOS.md, and the docs/ folder.
All custom code is under src/
To get started, run "rig project setup"
[ERROR] Error configuring file watches on Docker Machine: exit status 1
[ERROR] Error running project script 'setup': 1
```

When I use bin/start.sh I can get pretty far in the end I get. Everything goes smoothly until this part

```
Running "drush:install" (drush) task
Include /etc/drush/commands                                                                                                                                                                          
Failed to create database: ERROR 1130 (HY000): Host 'rigtest2_cli_run_1.build.vm' is not allowed to connect to this MariaDB server                                                                [error]
```

I'm sorry if I'm bothering you so much with my support requests I hope that's alright?
Omg this is all so confusing :)

**Comment by grayside** [comment]
rig start and bin/start.sh are different things. Rig start handles Outrigger's startup routine, which is adaptive to operating systems but can including starting up docker, docker-machine, the outrigger dashboard, DNS services, and more. To see everything that happens on your machine, run with `rig --verbose start`.

The generated `bin/start.sh` script when you use rig to create a project (which is in fact a simple wrapper around generator-outrigger-drupal as I mentioned above), currently has issues with both Linux and the Unison file sync we steer projects to for OSX and Windows. I expect to have something sorted out on that in the next week or two.

Across your issues it seems like you have a few different problems at once, so I hate to jump past the more basic environmental problems to bin/start.sh failing, but if you want to try work in progress, here are a few steps you can take:

1. Copy the contents of the [revisions-in-progress outrigger.yml template file](https://github.com/phase2/generator-outrigger-drupal/blob/0bc7d64861c74082535e78bfe0068bec0aa8fa03/generators/environment/templates/outrigger/outrigger.yml) over your .outrigger.yml file.
2. Do a replace all of `<%= projectName %>` with your selected project name. 
3. Run `rig project setup` instead of `bin/start.sh`.

This would really help confirm that I've fixed the basic Linux problem in the Drupal tooling part of the system.

**Comment by dmiric** [comment]
Still not working sorry.

```
➜  rigtest2 rig --verbose project setup
[VERBOSE] Executing 'setup': Run the end-to-end repository initialization and site install script.
[VERBOSE] Adding './bin:./node_modules/.bin:./vendor/bin' to the PATH for script execution.
[VERBOSE] Executing 'setup' as 'rig project run:welcome && echo "Continuing with 'rig project setup'..." && rig project sync:start && rig project build && rig project install && rig project run "grunt seed-users" && echo "Congratulations, your new <%= rigtest2 %> instance is fully set up." && echo "From now on, use 'rig project up' to start your work sessions." '
Welcome to the Project!
Please review the README.md, CONTRIBUTING.md, TODOS.md, and the docs/ folder.
All custom code is under src/
To get started, run "rig project setup"
Continuing with 'rig project setup'...
[ERROR] Error configuring file watches on Docker Machine: exit status 1
[ERROR] Error running project script 'setup': 1
```

```
➜  rigtest2 rig doctor
[ERROR] No machine named 'dev' exists. Did you run 'rig start --name="dev"'?
```

I know this should not matter but still maybe it helps.

```
➜  rigtest2 bin/doctor.sh
Docker Utilities
	[WARN] devtools command not found.
	[INFO] docker found
	[INFO] docker-compose found
	[INFO] docker-machine found
No active host found
	[INFO] No active
Code Generated with Yo Outrigger Drupal
	[INFO] src found
	[INFO] package.json found
	[INFO] composer.json found
	[INFO] docker-compose.yml found
	[INFO] build.yml found
Project Requirements Met
	[INFO] node_modules found
Code Generated by Grunt Drupal Tasks Build Process
	[INFO] build found
	[INFO] build/html found
	[INFO] build/html/index.php found
Docker-Machine Functionality
	[INFO] code volume-mount
➜  rigtest2 bin/doctor.sh
Docker Utilities
	[WARN] devtools command not found.
	[INFO] docker found
	[INFO] docker-compose found
	[INFO] docker-machine found
No active host found
	[INFO] No active
Code Generated with Yo Outrigger Drupal
	[INFO] src found
	[INFO] package.json found
	[INFO] composer.json found
	[INFO] docker-compose.yml found
	[INFO] build.yml found
Project Requirements Met
	[INFO] node_modules found
Code Generated by Grunt Drupal Tasks Build Process
	[INFO] build found
	[INFO] build/html found
	[INFO] build/html/index.php found
Docker-Machine Functionality
	[INFO] code volume-mount

```

**Comment by febbraro** [comment]
So there was a lot going on here, where are you currently stuck?  It sounds like you got past the `grunt not found` issue. (that was a problem with the named volume mount, and you are currently stuck with not being able to connect to mariadb from the build container?

**Comment by dmiric** [comment]
No I'm constantly stuck at not beeing able to use rig.

No machine named 'dev'. 

I can't use rig project setup.

All the steps I did pass is actually by using shell scripts in bin. But that's not how this is suppkse to work.;

**Comment by febbraro** [comment]
So, since you are on Linux ,you will never need a machine name 'dev', that is a Mac/Windows VM that runs boot2docker so it can run Docker.

If you look in .outrigger.yml at the `scripts.setup` command, you will see that it run a welcome (you dont need that) and it also run `rig project sync:start` which you also don't need, that is for the unison volumes which earlier we had you change your volume configuration to get rid of it.

So at the end of the day, all you need is to run `bin/start.sh` and you have the Linux version of the `project setup` script

Another option for you is to change the scripts in `.outrigger.yml` to remove all instances of `rig project sync:start` and `rig project sync:stop` since you don't need to unison volumes. Do that and then we can see if there are any other problems with getting a working environment.

**Comment by dmiric** [comment]
Yes thank you. I got it now rig is not for linux :) It would be awesome if you changed your documentation to reflect that. Since now it kinda takes 3 days for someone to figure that one out.

Thank younfor helping me figure this all out.

**Comment by grayside** [comment]
It's not that rig is not for Linux, it's that most of what it does is not for Linux and we clearly need to test further to make sure it does not attempt to do non-Linux things with Linux.

We are in progress on fixing the project generated by `rig project create` to be more Linux friendly which will help.

**Comment by dmiric** [comment]
Yes I understand. Anyway I'm willing to test the it again when it's ironed out a bit more. For now we will stick with acquia blt setup for our projects.

My intention was to find a docker setup we could use in conjunction with acquia blt, since docker support for blt is in experimental phase atm and not really robust.

Also, it would be cool if we could use rig like this:
rig drush cr
rig blt setup
rig drupal generate:entity

I know you can make an alias for that on linux but it would still be helpful it those things were integrated like that.

Atm there are as many solutions for drupal workflow as there are drupal companies joining forces would go a long way in soloving this problem.

**Comment by grayside** [comment]
Outrigger is not specifically targeted at Drupal. Rather, our initial library of images take care to support Drupal use cases. I now understand the perspective you brought on `rig project create`, which is the only Drupal-specific piece of rig.

What the generated project can do is add `rig project drupal` as a sort of built-in wrapper, but whether that's useful on top of the docker-compose wrapper we provide for many of those tools is less clear.

Good luck in your search!
